name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: tenderacr.azurecr.io
      IMAGE_TAG: ${{ github.sha }}
      RG_NAME: tender-rg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: tenderacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            tenderacr.azurecr.io/tender-api:${{ github.sha }}
            tenderacr.azurecr.io/tender-api:latest

      - name: Deploy using Bicep template
        run: |
          az deployment group create --resource-group ${{ env.RG_NAME }} --template-file infra/azuredeploy.bicep --parameters apiImage=tenderacr.azurecr.io/tender-api:${{ github.sha }}
