name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_TAG: ${{ github.sha }}
      RG_NAME: tender-rg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker images
        run: |
          docker build -t $REGISTRY/tender-api:$IMAGE_TAG -t $REGISTRY/tender-api:latest -f backend/Dockerfile .
          docker push $REGISTRY/tender-api:$IMAGE_TAG
          docker push $REGISTRY/tender-api:latest

      - name: Deploy using Bicep template
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az deployment group create \
              --resource-group $RG_NAME \
              --template-file infra/azuredeploy.bicep \
              --parameters apiImage=$REGISTRY/tender-api:$IMAGE_TAG \
                           workerImage=$REGISTRY/tender-api:$IMAGE_TAG
