name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_TAG: ${{ github.sha }}
      RG_NAME: tender-rg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Log in to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.tags.outputs.registry }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Set image tags
        id: tags
        run: |
          # Try different secret names and fallback to known registry
          REGISTRY="${{ secrets.ACR_LOGIN_SERVER }}"
          if [ -z "$REGISTRY" ]; then
            REGISTRY="${{ secrets.REGISTRY_LOGIN_SERVER }}"
          fi
          if [ -z "$REGISTRY" ]; then
            REGISTRY="tenderregistry.azurecr.io"
          fi
          IMAGE_TAG="${{ github.sha }}"
          echo "registry=${REGISTRY}" >> $GITHUB_OUTPUT
          echo "image-tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "full-tag=${REGISTRY}/tender-api:${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "latest-tag=${REGISTRY}/tender-api:latest" >> $GITHUB_OUTPUT
          echo "Registry used: ${REGISTRY}"
          echo "Image: tender-api:${IMAGE_TAG}"

      - name: Build and push Docker images
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ steps.tags.outputs.full-tag }}
            ${{ steps.tags.outputs.latest-tag }}

      - name: Deploy using Bicep template
        run: |
          az deployment group create --resource-group ${{ env.RG_NAME }} --template-file infra/azuredeploy.bicep --parameters apiImage=${{ env.REGISTRY }}/tender-api:${{ env.IMAGE_TAG }} workerImage=${{ env.REGISTRY }}/tender-api:${{ env.IMAGE_TAG }}
