name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.ACR_LOGIN_SERVER }}
      IMAGE_TAG: ${{ github.sha }}
      RG_NAME: tender-rg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        run: |
          az login --service-principal --username ${{ secrets.AZURE_CLIENT_ID }} --password ${{ secrets.AZURE_CLIENT_SECRET }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - name: Build and push Docker images
        run: |
          cd backend
          DOCKER_BUILDKIT=0 docker build -t $REGISTRY/tender-api:$IMAGE_TAG .
          docker tag $REGISTRY/tender-api:$IMAGE_TAG $REGISTRY/tender-api:latest
          docker push $REGISTRY/tender-api:$IMAGE_TAG
          docker push $REGISTRY/tender-api:latest

      - name: Deploy using Bicep template
        run: |
          az deployment group create --resource-group $RG_NAME --template-file infra/azuredeploy.bicep --parameters apiImage=$REGISTRY/tender-api:$IMAGE_TAG workerImage=$REGISTRY/tender-api:$IMAGE_TAG
